using Pkg

Pkg.add(name="Graphs",version="1.7.1")
Pkg.add(name="MetaGraphsNext",version="0.4.0")
Pkg.add(name="Distributions",version="0.25.90")
Pkg.add(name="StatsPlots",version="0.15.5")
Pkg.add(name="StochasticDiffEq",version="6.60.0")
Pkg.add(name="JSON",version="0.21.4")
Pkg.add(name="IfElse",version="0.1.1")
Pkg.add(name="DataStructures",version="0.18.13")
Pkg.add(name="Cairo",version="1.0.5")
Pkg.add(name="Colors",version="0.12.10")
Pkg.add(name="Compose",version="0.9.5")
Pkg.add(name="DifferentialEquations",version="7.7.0")
Pkg.add(name="GraphPlot",version="0.5.2")
Pkg.add(name="ModelingToolkit",version="8.55.1")
Pkg.add(name="ModelingToolkitStandardLibrary",version="1.16.0")
Pkg.add(name="OrdinaryDiffEq",version="6.51.1")
Pkg.add(name="Plots",version="1.38.11")
Pkg.add(name="QuadGK",version="2.8.2")
